### ISSUE TITLE
console不支持pyramid 1.6，换到1.4OK了

### ISSUE THREAD

**Issue by daimon99** [easydo-cn/ztq#2]
建议在setup中指定版本啊

**Comment by daimon99** [comment]
对了，我是pip从pypi安装的，不是从github安装的。

**Comment by daimon99** [comment]
访问又报这个错。。

## serving on 0.0.0.0:7005 view at http://127.0.0.1:7005

Exception happened during processing of request from ('127.0.0.1', 50090)
Traceback (most recent call last):
  File "/home/pyer/.virtualenvs/santi/lib/python2.7/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 655, in **init**
    self.handle()
  File "/home/pyer/.virtualenvs/santi/lib/python2.7/site-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/pyer/.virtualenvs/santi/lib/python2.7/site-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/home/pyer/.virtualenvs/santi/lib/python2.7/site-packages/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/home/pyer/.virtualenvs/santi/lib/python2.7/site-packages/weberror/evalexception.py", line 257, in **call**
    req_path = req.path_info.split('/')[1:len(self.debug_url_prefix + 1)]

## TypeError: can only concatenate list (not "int") to list
